# Generated by Django 4.0.2 on 2022-03-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recSys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menureview',
            name='review',
            field=models.BooleanField(null=True, verbose_name='like или dislike'),
        ),
    ]
