# Generated by Django 4.0.2 on 2022-03-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recSys', '0003_user_university_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menureview',
            name='Like_or_dislike',
            field=models.BooleanField(null=True, verbose_name='like или dislike'),
        ),
    ]
