# Generated by Django 4.0.2 on 2022-03-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recSys', '0004_menureview_like_or_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menureview',
            name='Like_or_dislike',
        ),
    ]
