# Generated by Django 4.0.2 on 2022-03-26 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recSys', '0006_delete_menureview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.BooleanField(null=True, verbose_name='like или dislike')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recSys.menu', verbose_name='menu_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
            options={
                'verbose_name': 'Лайк или дизлайк',
                'verbose_name_plural': 'Лайк или дизлайк',
                'db_table': 'menu_review',
            },
        ),
    ]
