# Generated by Django 4.0.2 on 2022-03-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recSys', '0008_rename_menu_id_menureview_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university_id',
            field=models.PositiveIntegerField(default=0, verbose_name='University_id'),
        ),
    ]
