# Generated by Django 4.0.2 on 2022-04-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recSys', '0010_menu_available_alter_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(max_length=300, upload_to='menu/', verbose_name='Картинка'),
        ),
    ]
