# Generated by Django 4.0.2 on 2022-04-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recSys', '0011_alter_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_type',
            field=models.CharField(choices=[('FO', 'блюда'), ('DR', 'напитки'), ('DE', 'десерт'), ('CO', 'комбо')], help_text='Тип еды', max_length=2, verbose_name='Тип еды'),
        ),
    ]
