# Generated by Django 4.0.2 on 2022-04-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recSys', '0012_alter_menu_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_type',
            field=models.CharField(choices=[('FO', 'Блюда'), ('DR', 'Напитки'), ('DE', 'Десерты'), ('CO', 'Комбо')], help_text='Тип еды', max_length=2, verbose_name='Тип еды'),
        ),
    ]
