# Generated by Django 4.0.2 on 2022-04-16 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recSys', '0013_alter_menu_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotioncoefficient',
            name='coefficient',
            field=models.FloatField(default=0, verbose_name='Коэффициент по эмоции'),
        ),
        migrations.AlterField(
            model_name='emotioncoefficient',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recSys.menu', verbose_name='Блюдо, напиток и т.д. из меню'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='final_coefficient',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Итоговый коэффициент'),
        ),
        migrations.AlterField(
            model_name='timecoefficient',
            name='coefficient',
            field=models.FloatField(default=0, verbose_name='Коэффициент по времени'),
        ),
        migrations.AlterField(
            model_name='timecoefficient',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recSys.menu', verbose_name='Блюдо, напиток и т.д. из меню'),
        ),
    ]
