# Generated by Django 4.0.2 on 2022-04-29 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recSys', '0014_alter_emotioncoefficient_coefficient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='Тип еды подробнее')),
            ],
            options={
                'verbose_name': 'Тип еды подробнее',
                'verbose_name_plural': 'Тип еды подробнее',
                'db_table': 'food_type',
            },
        ),
        migrations.AlterModelOptions(
            name='emotioncoefficient',
            options={'verbose_name': 'Коэффициент настроения', 'verbose_name_plural': 'Коэффициенты настроения'},
        ),
        migrations.AlterModelOptions(
            name='timecoefficient',
            options={'verbose_name': 'Коэффициент время', 'verbose_name_plural': 'Коэффициенты время'},
        ),
        migrations.AddField(
            model_name='menu',
            name='food_type_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recSys.foodtype', verbose_name='Тип еды подробнее'),
        ),
    ]
