# Generated by Django 4.0.2 on 2022-05-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recSys', '0016_rename_foodtype_foodtypedetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='final_coefficient',
            field=models.SmallIntegerField(default=0, verbose_name='Итоговый коэффициент'),
        ),
    ]
