# Generated by Django 4.0.2 on 2022-03-24 19:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.CharField(default='/resources/static/img/table-tennis.jpg', max_length=300, verbose_name='Ссылка на картинку')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
                'db_table': 'table',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateField(default=datetime.date.today, verbose_name='Дата создания бронирования')),
                ('date_of_reservation', models.DateField(verbose_name='Дата бронирования')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирование',
                'db_table': 'reservation',
            },
        ),
    ]
