# Generated by Django 4.0.2 on 2022-03-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='user_id',
            new_name='user',
        ),
    ]
