# Generated by Django 4.0.2 on 2022-03-27 19:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_table_id_reservation_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time_of_reservation',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_of_reservation',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата бронирования'),
        ),
    ]
