# Generated by Django 4.0.2 on 2022-04-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_time_of_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='image',
            field=models.ImageField(max_length=300, upload_to='tables/', verbose_name='Картинка'),
        ),
    ]
